# config file for sourcemanager

# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
log_level: 1

# gte=1,lte=1000
job_works: 8

zeppelin_server: "127.0.0.1:8080"
zeppelin_flink_home: "/home/lzzhang/bigdata/flink-bin-download/flink-1.11.2"
zeppelin_flink_execute_jars: "/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/flink-connector-jdbc_2.11-1.11.2.jar,/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/mysql-connector-java-8.0.21.jar,/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/postgresql-42.2.18.jar,/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/flink-sql-connector-kafka_2.11-1.11.2.jar,/home/lzzhang/bigdata/flink-bin-download/zeppelin-0.9.0-bin-all/lib/flink-connector-clickhouse-1.11.0.jar"

sourcemanager_server: "127.0.0.1:50001"

grpc_server:
  address: "127.0.0.1:51001"  # required
  log_level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  log_verbosity: 9

metrics_server:
  enabled: true
  address: "127.0.0.1:51002" # required when enabled is true
  url_path: "/metrics"

mysql:
  hosts: "127.0.0.1:3306"  # required
  users: "root"  # required
  password: "123456"  # required
  database: "data_workbench"  # required
  max_idle_conn: 16
  max_open_conn: 128
  conn_max_lifetime: 10m
  log_level: 4 # 1 => Silent, 2 => Error, 3 => Warn, 4 => Info
  slow_threshold: 2s
