# config file for sourcemanager

# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
log_level: 1
zeppelin_address: "http://127.0.0.1:8080"

enginemanager_server:
  address: "127.0.0.1:9114"  # required
  log_level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  log_verbosity: 99
udfmanager_server:
  address: "127.0.0.1:9106"
  log_level: 2
  log_verbosity: 99
resourcemanager_server:
  address: "127.0.0.1:9111"
  log_level: 2
  log_verbosity: 99

grpc_server:
  address: "127.0.0.1:9105"  # required
  log_level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  log_verbosity: 99

metrics_server:
  enabled: true
  address: "127.0.0.1:9205" # required when enabled is true
  url_path: "/metrics"

tracer:
  service_name: "jobmanager"
  local_agent: "127.0.0.1:6831"
